warning_threshold: 15
maxEmptyLines: 3

excluded:
 - Pods

disabled_rules:
 - trailing_whitespace

line_length:
  warning: 180

function_parameter_count:
  warning: 10
  error: 15

file_length:
  warning: 500

type_body_length:
  warning: 400
  error: 450

cyclomatic_complexity:
  warning: 12
  error: 15

vertical_whitespace:
  max_empty_lines: 3
  severity: error  
