# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  desc "Build application"
  lane :build do
    gym(
      project: "xibdump.xcodeproj", 
      configuration: "Release", 
      scheme: "xibdump",
      clean: true, 
      output_name: "xibdump",
      output_directory: "./release"
      )
  end
end
